---
title: "Partitioning Around Medoids(PAM)"
author: "Nidhin"
date: "25/07/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load the dataset
data=USArrests
```

```{r}
#Check the dataset
str(data)
head(data)
```
```{r}
#Scale the data for standardization
df <- scale(USArrests) 
head(df)
```

```{r}
#Load the required Libraries
library(cluster)
library(factoextra)
```

```{r}
#Estimating the optimal number of clusters
fviz_nbclust(df,pam,method="silhouette")

```

```{r}
#Computing PAM clustering

pam.model<- pam(df,2)
print(pam.model)
```

```
#Accessing to the results of the pam() function
pam.model$medoids
pam.model$clustering
pam.model$data
pam.model$clusinfo
```

```{r}
#add the point classifications to the original data
dd <- cbind(USArrests, cluster = pam.model$cluster)
dd
```
```{r}
#Visualizing PAM clusters
library(factoextra)
fviz_cluster(pam.model
,
palette = c("#00AFBB", "#FC4E07"), # color palette
ellipse.type = "t", # Concentration ellipse
repel = TRUE, # Avoid label overplotting (slow)
ggtheme = theme_classic()
)
```

